debug: false
uuid: 890a5dd8-b0cc-484b-b2e6-318b663235d5
token_id: gVM6IO487vLi9vHz
token: dhYBhJj4Mep8sHCrz85L6gkRtMb4ll0bcecZhbDnnX57FwcRwBYY8fQNgX6vOSGG
api:
  host: 0.0.0.0
  port: 8080
  ssl:
    enabled: false
    cert: /etc/letsencrypt/live/node.stucraftsmp.net/fullchain.pem
    key: /etc/letsencrypt/live/node.stucraftsmp.net/privkey.pem
  upload_limit: 100
system:
  data: /var/lib/pterodactyl/volumes
  sftp:
    bind_port: 2022
allowed_mounts: []
remote: 'https://panel.stucraftsmp.net'